# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "dingyufan"
email = "dingyufan@outlook.com"
link = "https://github.com/dingyufan"
avatar = "/images/profile-picture.jpg"
